blank_issues_enabled: true
contact_links:
  - name: Infrastructure issue
    url: https://github.com/jenkins-infra/helpdesk/issues
    about: Check if there isn't already an issue open in the Jenkins Infrastructure Help Desk first
  - name: Community forum
    url: https://community.jenkins.io/tag/sig-infra
    about: Please ask and answer questions here
  - name: Mailing lists
    url: https://www.jenkins.io/mailing-lists/#jenkins-infra-googlegroups-com
    about: You can also raise a question in Jenkins Infrastructure mailing list
