blank_issues_enabled: true
contact_links:
  - name: Community forum
    url: https://community.jenkins.io/tag/sig-infra
    about: Please ask and answer questions here
  - name: Mailing lists
    url: https://www.jenkins.io/mailing-lists/#jenkins-infra-googlegroups-com
    about: You can also raise a question in Jenkins Infrastructure mailing list
